# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GpsPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.TextField(blank=True, default='standard')),
                ('orientation', models.TextField(blank=True, default='')),
                ('shape', models.TextField(blank=True, default='')),
                ('background_color', models.TextField(blank=True, default='')),
                ('alphanumeric', models.TextField(blank=True, default='')),
                ('alphanumeric_color', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail', models.ImageField(blank=True, upload_to='targets')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modifified_time', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vision.GpsPosition')),
            ],
        ),
    ]
